- name: Add {{ user_name }} into "docker" group
  become: true
  user:
    name: "{{ user_name }}"
    groups: docker
    append: true
- name: Clone git repo
  become: true
  git:
    repo: "{{ git_clone_url }}"
    dest: /home/{{ user_name }}/git
    version: "{{ git_branch }}"
    force: yes
  register: git_clone_result
- name: Install service
  block:
    - name: Stop {{ user_name }}-service
      systemd:
        name: "{{ user_name }}-service.service"
        state: stopped
      ignore_errors: true
    - name: Docker-compose build
      command:
        cmd: "docker-compose build"
        chdir: /home/{{ user_name }}/git
    - name: Create {{ user_name }}-service
      template:
        src: service.service.j2
        dest: /etc/systemd/system/{{ user_name }}-service.service
        mode: '755'
    - name: Restart systemd (reread configs)
      systemd:
        daemon_reload: true
    - name: Install our service
      systemd:
        name: "{{ user_name }}-service.service"
        enabled: true
        masked: false
        state: started
  when: git_clone_result.changed
  become: true
