- name: Clone git repo
  become: true
  git:
    repo: "{{ git_clone_url }}"
    dest: /home/{{ user_name }}/git
    version: "{{ git_branch }}"
    force: yes
- name: docker-compose build
  become: true
  command:
    cmd: "docker-compose up -d"
    chdir: /home/{{ user_name }}/git

