version: '3.4'
services:
  authz:
    #    image: dmitry231187/hw25:latest
    container_name: authz
    build: /home/authz/git
  nginx:
    container_name: nginx
    build: ./nginx
    restart: 'always'
    ports:
      - "80:80"

