---
# tasks file for create_user

- name: Create "{{ user_name }}" user
  user:
    name: "{{ user_name }}"
    groups: sudo, adm
    shell: /bin/bash
    password: "{{ user_passwd }}"
    append: yes
  become: true
