- name: Check cloned git
  become: true
  stat:
    path: /home/{{ user_name }}/git
  register: repo_result
- name: Clone git repo
  become: true
  git:
    repo: "{{ git_clone_url }}"
    dest: /home/authz/git
    version: master
    force: yes
- name: Poetry project install
  become: true
  become_user: "{{ user_name }}"
  shell: poetry install chdir=/home/{{ user_name }}/git
  when: repo_result.stat.exists == False
