- name: Create {{ user_name }}-service
  become: true
  template:
    src: service.service.j2
    dest: /etc/systemd/system/{{ user_name }}-service.service
    mode: '755'
      #  notify:
    #  dd  trigger_service: true
      #- name: Start {{ user_name }}-service.service
      #  become: true
      #  command: systemctl start {{ user_name }}-service.service
- name: Install our service
  become: true
  systemd:
    name: "{{ user_name }}-service.service"
    enabled: true
    masked: false
    state: started
